registerAPI.rest.url: http://restapi.demoqa.com/customer/register
fetchWeatherDetailsAPI.rest.url: http://restapi.demoqa.com/utilities/weather/city/Hyderabad
petStore.rest.url: https://petstore.swagger.io/v2